finalprojectthp-staging/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :patients
  devise_for :practionners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
end

finalprojectthp-staging/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

finalprojectthp-staging/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :practionner
  belongs_to :patient

  after_create :patient_send_email, :practionner_send_email

  def patient_send_email
  	AppointmentMailer.patient_email(self).deliver_now
  end

  def practionner_send_email
  	AppointmentMailer.practionner_email(self).deliver_now
  end

end

finalprojectthp-staging/app/models/day.rb
class Day < ApplicationRecord
  has_many :data_shows, dependent: :delete_all #This line enable to create a seed without problem
  has_many :patients, through: :data_shows
end

finalprojectthp-staging/app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :appointments, dependent: :delete_all #This line enable to create a seed without problem
  has_many :practionners, through: :appointments

  has_many :data_shows, dependent: :delete_all
  has_many :days, through: :data_shows

  after_create :welcome_send

  def welcome_send
    PatientMailer.welcome_email(self).deliver_now
  end

end

finalprojectthp-staging/app/models/practionner.rb
class Practionner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :appointments, dependent: :delete_all #This line enable to create a seed without problem
  has_many :patients, through: :appointments

  after_create :welcome_send

  def welcome_send
    PractionnerMailer.welcome_email(self).deliver_now
  end

end

finalprojectthp-staging/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

finalprojectthp-staging/app/helpers/application_helper.rb
module ApplicationHelper
end

finalprojectthp-staging/app/helpers/home_helper.rb
module HomeHelper
end

finalprojectthp-staging/app/views/home/index.html.erb
<ul>
  <% if practionner_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_practionner_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_practionner.email %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_practionner_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_practionner_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_practionner_registration_path %>
    </li>

  <% end %>
</ul>

finalprojectthp-staging/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">

  <head>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



  </head>

  <body>

    <%= yield %>

    <!-- Bootstrap core JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>

</html>