config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :patients
  devise_for :practionners
  resources :patients 
  resources :practionners
  resources :patient_list
  resources :doctor_appointment_list
  resources :days
  resources :appointments

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :practionner
  belongs_to :patient

  after_create :patient_send_email, :practionner_send_email
  
  validates :date, presence: true
  validates :place, presence: true 

  def patient_send_email
  	AppointmentMailer.patient_email(self).deliver_now
  end

  def practionner_send_email
  	AppointmentMailer.practionner_email(self).deliver_now
  end

end

app/models/data_show.rb
class DataShow < ApplicationRecord
  belongs_to :day
  belongs_to :patient
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :data_shows, dependent: :delete_all #This line enable to create a seed without problem
  has_many :patients, through: :data_shows

  validates :date, presence: true
  validates :hours_of_sleep, presence: true, length: {maximum: 2}
  validates :mood, presence: true
  validates :treatment, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
	after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :appointments, dependent: :delete_all #This line enable to create a seed without problem
  has_many :practionners, through: :appointments

  has_many :data_shows, dependent: :delete_all
  has_many :days, through: :data_shows

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :treatment, length: { maximum: 200 }

  def welcome_send
    PatientMailer.welcome_email(self).deliver_now
  end

end

app/models/practionner.rb
class Practionner < ApplicationRecord
	after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :appointments, dependent: :delete_all #This line enable to create a seed without problem
  has_many :patients, through: :appointments

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :specialty, length: { maximum: 300 }
  validates :adress, presence: true

  def welcome_send
    PractionnerMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_parameters, if: :devise_controller?

		 protected
     def after_sign_in_path_for(ressource)
     if current_patient
         patient_path(ressource)
     else current_practionner
         practionner_path(ressource)
     end
	 	 end

         
     def configure_devise_parameters
       devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
       devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
     end
 end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	def new
		@appointment = Appointment.new
	end

	def create
		@appointment = Appointment.new(date: params[:date], place: params[:place], patient_id: params[:patient_id], practionner_id: params[:practionner_id])
		if @appointment.save
		redirect_to doctor_appointment_list_path(current_patient.id)
		else
		redirect_to root_path

		end
	end
end

app/controllers/avatars_patient_controller.rb
class AvatarsPatientController < ApplicationController

	def create
    @patient = Patient.find(params[:patient_id])
    @patient.avatar.purge
    @patient.avatar.attach(params[:avatar])
    redirect_to(edit_patient_path(@patient))
 	end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

	def new
		@day = Day.new
	end

	def create
		@day = Day.new(mood: params[:mood], hours_of_sleep: params[:hours_of_sleep])
		if @day.save
		redirect_to patient_path(current_patient.id)
		else
		redirect_to root_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end


end

app/controllers/patient_list_controller.rb
class PatientListController < ApplicationController
before_action :authorize_user

  def show
  	@practionner_patients = Practionner.find(params[:id]).patients
  end

  private

  def authorize_user 
    @user = Practionner.find(params[:id])
    unless current_practionner == @user
      flash[:danger] = "Veuillez vous connecter."
      redirect_to new_practionner_session_path
    end
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_action :authorize_user, except: [:index]

  def index
    
  end

  def show
  	@patient_day = Patient.find(params[:id]).days
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient = Patient.update(patient_params)
    redirect_to edit_patient_path
    else
    render 'modifier'
    end 
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name,:last_name, :treatment, :city, :birth, :sexe)
  end

  def authorize_user 
    @user = Patient.find(params[:id])
    @user_practionner = @user.practionners

    @user_practionner.each do |practionner|
      if practionner == current_practionner
        @count = 1
      end
    end

    if @user == current_patient
      @count = 1
    end

    if @count != 1
      flash[:danger] = "Veuillez vous connecter."
      redirect_to new_patient_session_path
    else
    end
  end

end

app/controllers/practionners_controller.rb
class PractionnersController < ApplicationController
before_action :authorize_user, except: [:index]

  def index
    @id_user = current_practionner.id
  end

  def show
  	@patients_of_the_day = Practionner.find(params[:id]).patients
  end

  def edit
    @practionner = Practionner.find(params[:id])
  end

  def update
    @practionner = Practionner.find(params[:id])
    if @practionner = Practionner.update(practionner_params)
    redirect_to edit_practionner_path
    else
    render 'modifier'
    end 
  end
  
  private

  def practionner_params
    params.require(:practionner).permit(:first_name, :last_name, :specialty, :adress, :sexe, :diploma, :certifications)
  end


	def authorize_user 
    @user = Practionner.find(params[:id])
    unless current_practionner == @user
      flash[:danger] = "Veuillez vous connecter."
      redirect_to new_practionner_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def current_practionner_avatar(current_practionner)
		if current_practionner.avatar.attached?
			current_practionner.avatar
		else
			gravatar_image_url(current_practionner.email)
		end
	end

	def current_patient_avatar(current_patient)
		if current_patient.avatar.attached?
			current_patient.avatar
		else
			gravatar_image_url(current_patient.email)
		end
	end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/avatars_patient_helper.rb
module AvatarsPatientHelper
end

app/helpers/avatars_practionner_helper.rb
module AvatarsPractionnerHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/patient_list_helper.rb
module PatientListHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practionners_helper.rb
module PractionnersHelper
end

app/views/home/index.html.erb
  <!-- portail de connexion -->
<section id="bipolink">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark " id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top"><img class="mx-auto" src="https://i.goopics.net/PgPnd.png" alt=""></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#application">Application</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#bipolarity">La maladie</a>
            </li>
            <li class="nav-item">
              <%if patient_signed_in? %>
                <%= render 'layouts/navbar-patient' %>
              <% end %>
            </li>
          </li>
          <li class="nav-item">
            <%if practionner_signed_in? %>
              <%= render 'layouts/navbar-practionner' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="row">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading text-uppercase">BipoLink</h2>
      <h4 class="section-subheading">Application de suivi de la bipolarité</h4>
       <br>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-md-6">
      <h4 class="section-heading"> Vous êtes</h4>
      <h3 class="section-subheading">un patient</h3>
      <img class="mx-auto rounded-circle" src="https://i.goopics.net/3KnvQ.png" alt=""><br>
      <br>
      <div class="text-center">
        <% if patient_signed_in? %>
          <%= link_to "Se déconnecter", destroy_patient_session_path, class:"link_color-bipolink", method: :delete %>
        <% else %>
          <button class="btn btn-light btn-xl text-uppercase js-scroll-trigger"> <%= link_to "Connexion",root_path, class:"button_color-bipolink" %></button>
          <p><%= link_to "Pas encore inscrit ?", root_path, class:"link_color-bipolink" %></p>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <h4 class="section-heading"> Vous êtes</h4>
      <h3 class="section-subheading">un professionel de santé</h3>
      <img class="mx-auto rounded-circle" src="https://i.goopics.net/nyPvX.png" alt=""><br>
      <br>
      <div class="text-center">
        <% if practionner_signed_in? %>
          <%= link_to "Se déconnecter", destroy_practionner_session_path, class:"link_color-bipolink", method: :delete %>
        <% else %>
          <button class="btn btn-light text-uppercase js-scroll-trigger"> <%= link_to "Connexion", root_path, class:"button_color-bipolink" %></button>
          <p class="text-muted"><%= link_to "Pas encore inscrit ?", root_path, class:"link_color-bipolink" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</section>
<!-- prez application -->
<section class="page-section" id="application">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="section-heading text-uppercase">BipoLink</h2>
         <br>
         <br>
         <br>
         <br>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <img class="mx-auto" src="https://i.goopics.net/w3vN3.png" alt="">
      </div>
      <div class="col-md-6">
        <h3>Un suivi facile en quelques clics !</h3>
        <br>
        <p class="text-muted">Bipolink, votre application compagnon pour vous suivre au quotidien.<br><br> L'application vous permet de renseigner un ensemble d'informations pour suivre l'évolution de votre état physique et mental. Si vous le souhaitez, vous pourrez également partager ces informations avec vos soignants. Des données qui permettront d'affiner le diagnostic et d'améliorer le suivi de la maladie. </p>
         <br>
         <br>
        <h4>Télécharger l'application :</h4>
        <br>
        <div class="applications">
          <a target="_blank" href="https://www.apple.com/fr/ios/app-store/">
            <img class="appli" src="https://i.goopics.net/RZXQV.jpeg">
          </a>
          <a target="_blank" href="https://play.google.com/store?gl=FR&utm_source=emea_Med&utm_medium=hasem&utm_content=Oct2019&utm_campaign=Evergreen&pcampaignid=MKT-DR-emea-fr-1001280-Med-hasem-py-Evergreen-Oct2019-Text_Search_BKWS-test_exp_ISTest2%7cONSEM_kwid_43700048881599560&gref=EkQKPAoICIDyou8FEBsSLAAT9nM92TYq_hLPWGd2ihMm97sLLaxBKYlIT_fCogU1KyEJ-Kz4NWHzlpWeGgIrexAC8P8HARjj9tyaAw&gclid=CjwKCAiA8qLvBRAbEiwAE_ZzPdk2Kv4Sz1hndooTJve7Cy2sQSmJSE_3wqIFNSshCfis-DVh85aVnhoCK3sQAvD_BwE&gclsrc=aw.ds">
            <img class="appli" src="https://i.goopics.net/ALYQo.jpeg">
          </a>
        </div>
      </div>
    </div>
  </section>
 <!-- la maladie -->
   <section class="bg-light page-section" id="bipolarity">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h2 class="section-heading text-uppercase">La bipolarité</h2> <br>
          <p class="text-muted">Maladie mentale chronique, les troubles bipolaires touchent entre 1 et 2,5 % de la population. Ils apparaissent majoritairement entre 15 et 25 ans et persistent toute la vie. Les malades présentant une espérance de vie réduite de 10 ans en moyenne par rapport à la population générale. Les épisodes dépressifs peuvent fréquemment déboucher sur des tentatives de suicide : 20% des patients bipolaires non traités décèdent par suicide. Par ailleurs, les troubles bipolaires s’accompagnent d’une forte comorbidité, c’est-à-dire que d’autres troubles se greffent à la maladie (alcoolisme, diabète, dysthyroïdie, etc.), faisant par exemple encourir aux patients le risque de succomber à d’autres pathologies, une maladie cardiovasculaire par exemple. Enfin, les conduites à risque (sexualité, addictions, dépenses) sont fréquentes et associées au handicap.
          <br><br>
          Mais c’est le retard de diagnostic qui pénalise le plus les patients. On estime à 10 ans en moyenne le temps écoulé entre un premier épisode et l’instauration d’un traitement adapté. Ce décalage s’explique par la méconnaissance de la maladie de la part des médecins, qui associent souvent les symptômes de la bipolarité à ceux de la dépression. Si bien qu’actuellement, 40 % des dépressifs pourraient en réalité souffrir de bipolarité sans être diagnostiqués.</p> 
          <br> <br>
        </div>
      </div>
      <h2 class="section-heading text-uppercase">En quelques chiffres</h2> <br> <br> <br>
      <div class="row text-center">
        <div class="col-md-4">
          <h2>1 M </h4>
          <p class="text-muted">de patients bipolaires estimés en France</p>
        </div>
        <div class="col-md-4">
          <h2>10 ans</h4>
          <p class="text-muted">le temps écoulé entre un premier épisode et l’instauration d’un traitement adapté</p>
        </div>
        <div class="col-md-4">
          <h2>6 ème</h4>
          <p class="text-muted">au rang mondial des handicaps</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Footer -->
<footer class="footer">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-4">
        <span class="copyright text-muted">Copyright &copy; Bipolink 2019</span>
      </div>
    </div>
  </div>
</footer>
</body>