config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  devise_for :patients
  devise_for :practionners
  resources :patients 
  resources :practionners
  resources :patient_list
  resources :doctor_appointment_list
  resources :days
  resources :appointments

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :practionner
  belongs_to :patient

  after_create :patient_send_email, :practionner_send_email
  
  validates :date, presence: true
  validates :place, presence: true 

  def patient_send_email
  	AppointmentMailer.patient_email(self).deliver_now
  end

  def practionner_send_email
  	AppointmentMailer.practionner_email(self).deliver_now
  end

end

app/models/data_show.rb
class DataShow < ApplicationRecord
  belongs_to :day
  belongs_to :patient
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :data_shows, dependent: :delete_all #This line enable to create a seed without problem
  has_many :patients, through: :data_shows

  validates :date, presence: true
  validates :hours_of_sleep, presence: true, length: {maximum: 2}
  validates :mood, presence: true
  validates :treatment, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
	after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :appointments, dependent: :delete_all #This line enable to create a seed without problem
  has_many :practionners, through: :appointments

  has_many :data_shows, dependent: :delete_all
  has_many :days, through: :data_shows

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :treatment, length: { maximum: 200 }

  def welcome_send
    PatientMailer.welcome_email(self).deliver_now
  end

end

app/models/practionner.rb
class Practionner < ApplicationRecord
	after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :appointments, dependent: :delete_all #This line enable to create a seed without problem
  has_many :patients, through: :appointments

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :specialty, length: { maximum: 300 }
  validates :adress, presence: true

  def welcome_send
    PractionnerMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_parameters, if: :devise_controller?

		 protected
     def after_sign_in_path_for(ressource)
     if current_patient
         patient_path(ressource)
     else current_practionner
         practionner_path(ressource)
     end
	 	 end

         
     def configure_devise_parameters
       devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
       devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
     end
 end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	def new
		@appointment = Appointment.new
	end

	def create
		@appointment = Appointment.new(date: params[:date], place: params[:place], patient_id: params[:patient_id], practionner_id: params[:practionner_id])
		if @appointment.save
		redirect_to doctor_appointment_list_path(current_patient.id)
		else
		redirect_to root_path

		end
	end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

	def new
		@day = Day.new
	end

	def create
		@day = Day.new(mood: params[:mood], hours_of_sleep: params[:hours_of_sleep])
		if @day.save
		redirect_to patient_path(current_patient.id)
		else
		redirect_to root_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end


end

app/controllers/patient_list_controller.rb
class PatientListController < ApplicationController
before_action :authorize_user

  def show
  	@practionner_patients = Practionner.find(params[:id]).patients
  end

  private

  def authorize_user 
    @user = Practionner.find(params[:id])
    unless current_practionner == @user
      flash[:danger] = "Veuillez vous connecter."
      redirect_to new_practionner_session_path
    end
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_action :authorize_user, except: [:index]

  def index
    
  end

  def show
  	@patient_day = Patient.find(params[:id]).days
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient = Patient.update(patient_params)
    redirect_to edit_patient_path
    else
    render 'modifier'
    end 
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name,:last_name, :treatment, :city, :birth, :sexe)
  end

  def authorize_user 
    @user = Patient.find(params[:id])
    @user_practionner = @user.practionners

    @user_practionner.each do |practionner|
      if practionner == current_practionner
        @count = 1
      end
    end

    if @user == current_patient
      @count = 1
    end

    if @count != 1
      flash[:danger] = "Veuillez vous connecter."
      redirect_to new_patient_session_path
    else
    end
  end

end

app/controllers/practionners_controller.rb
class PractionnersController < ApplicationController
before_action :authorize_user, except: [:index]

  def index
    @id_user = current_practionner.id
  end

  def show
  	@patients_of_the_day = Practionner.find(params[:id]).patients
  end

  def edit
    @practionner = Practionner.find(params[:id])
  end

  def update
    @practionner = Practionner.find(params[:id])
    if @practionner = Practionner.update(practionner_params)
    redirect_to edit_practionner_path
    else
    render 'modifier'
    end 
  end
  
  private

  def practionner_params
    params.require(:practionner).permit(:first_name, :last_name, :specialty, :adress, :sexe, :diploma, :certifications)
  end


	def authorize_user 
    @user = Practionner.find(params[:id])
    unless current_practionner == @user
      flash[:danger] = "Veuillez vous connecter."
      redirect_to new_practionner_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def current_practionner_avatar(current_practionner)
		if current_practionner.avatar.attached?
			current_practionner.avatar
		else
			gravatar_image_url(current_practionner.email)
		end
	end

	def current_patient_avatar(current_patient)
		if current_patient.avatar.attached?
			current_patient.avatar
		else
			gravatar_image_url(current_patient.email)
		end
	end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/avatars_patient_helper.rb
module AvatarsPatientHelper
end

app/helpers/avatars_practionner_helper.rb
module AvatarsPractionnerHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/patient_list_helper.rb
module PatientListHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practionners_helper.rb
module PractionnersHelper
end

app/views/layouts/_navbar-patient.html.erb
 <div class="dropdown">
  <img src="https://i.redd.it/6onq25y0sh311.jpg" class="float-left rounded-circle avatar-sm">
  <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Mon compte
  </button>
  <div class="dropdown-menu">
    <%= link_to "Mon dashboard", patient_path(current_patient.id) %><br>
    <%= link_to "Paramètres", edit_patient_registration_path(current_patient.id) %>
    <div class="dropdown-divider"></div>
    <%= link_to "Se déconnecter", destroy_patient_session_path, method: :delete %>
  </div>
</div>
</div>
</nav>
<!-- Dropdown Toggle -->
<script>
  $('.dropdown-toggle').dropdown()
</script>

app/views/layouts/_navbar-practionner.html.erb
<div class="dropdown">
  <img src="https://i.redd.it/6onq25y0sh311.jpg" class="float-left rounded-circle avatar-sm">
  <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Mon compte
  </button>
  <div class="dropdown-menu">
    <%= link_to "Mon dashboard", practionner_path(current_practionner.id) %><br>
    <%= link_to "Paramètres", edit_practionner_registration_path(current_practionner.id) %>
    <div class="dropdown-divider"></div>
    <%= link_to "Se déconnecter", destroy_patient_session_path, method: :delete %>
  </div>
</div>
</div>
</nav>
<!-- Dropdown Toggle -->
<script>
  $('.dropdown-toggle').dropdown()
</script>

app/views/layouts/_side-navbar-doctor.html.erb
<div class="wrapper">
  <!-- Sidebar  -->
  <nav id="sidebar">
    <div class="sidebar-header">
      <img src="https://i.ibb.co/PmfTM9j/Moodlinkv3.png" class="logo-size">
    </div>
    <ul class="list-group">
      <li class="active">
        <div id="sidebarCollapse">
          <div id="nav-icon3" id="sidebarCollapse">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div class="navbar-text-color">
          <div class="nav-link">
            <div class="media align-items-center">
              <%= link_to ('<i class="far fa-calendar-plus fa-2x icon-perso"></i>'.html_safe), practionner_path(current_practionner.id), class: "link_color-icon" %>
              <%= link_to "Mon dashboard", practionner_path(current_practionner.id), class: 'link_color-sidebar' %>
            </div>
          </div>
          <div class="nav-link">
            <div class="media align-items-center">
              <%= link_to ('<i class="fas fa-users fa-2x icon-perso"></i>'.html_safe), patient_list_path(current_practionner.id), class: "link_color-icon" %>
              <%= link_to "Mes patients", patient_list_path(current_practionner.id), class: 'link_color-sidebar' %>
            </div>
          </div>
          <div class="nav-link">
            <div class="media align-items-center">
              <%= link_to ('<i class="fas fa-user-md fa-2x icon-perso"></i>'.html_safe), practionners_path, class: "link_color-icon" %>
              <%= link_to "Mon profil", practionners_path, class: 'link_color-sidebar' %>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </nav>
  <!-- Sidebar Toggle JS script-->
  <script>
    $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
  </script>

app/views/layouts/_side-navbar-patient.html.erb
<div class="wrapper">
  <!-- Sidebar  -->
  <nav id="sidebar">
    <div class="sidebar-header">
      <img src="https://i.ibb.co/PmfTM9j/Moodlinkv3.png" class="logo-size">
    </div>
    <ul class="list-group">
      <li>
        <div id="sidebarCollapse">
          <div id="nav-icon3" id="sidebarCollapse">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div class="navbar-text-color">
          <div class="nav-link">
            <div class="media align-items-center">
              <%= link_to ('<i class="fas fa-chart-bar fa-2x"></i>'.html_safe), patient_path(current_patient.id), class: "link_color-icon" %>
              <%= link_to "Mon dashboard", patient_path(current_patient.id), class: 'link_color-sidebar' %>
            </div>
          </div>
          <div class="nav-link">
            <div class="media align-items-center">
              <%= link_to ('<i class="fas fa-user-md fa-2x icon-perso"></i>'.html_safe), doctor_appointment_list_path(current_patient.id), class: "link_color-icon" %>
              <%= link_to "Mes soignants et RDV", doctor_appointment_list_path(current_patient.id), class: 'link_color-sidebar' %>
            </div>
          </div>
          <div class="nav-link">
            <div class="media align-items-center">
              <%= link_to ('<i class="fas fa-user fa-2x icon-perso"></i>'.html_safe), patients_path, class: "link_color-icon" %>
              <%= link_to "Mon profil", patients_path, class: 'link_color-sidebar' %>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </nav>
  <!-- Sidebar Toggle JS script-->
  <script>
    $(document).ready(function () {
    
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
    
        });
  </script>

app/views/layouts/_side-navbar.html.erb
<!-- Sidebar  -->
<nav id="sidebar">
  <div class="sidebar-header">
    <img src="https://i.ibb.co/PmfTM9j/Moodlinkv3.png" class="logo-size">
  </div>
  <ul class="list-group">
    <li>
      <div id="sidebarCollapse">
        <div id="nav-icon3" id="sidebarCollapse">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div class="navbar-text-color">
        <div class="nav-link">
          <div class="media align-items-center">
            <%= link_to ('<i class="fas fa-chart-bar fa-2x"></i>'.html_safe), root_path, class: "link_color-icon" %>
            <%= link_to "Mon dashboard", root_path, class: 'link_color-sidebar' %>
          </div>
        </div>
        <div class="nav-link">
          <div class="media align-items-center">
            <%= link_to ('<i class="fas fa-user-md fa-2x icon-perso"></i>'.html_safe), root_path, class: "link_color-icon" %>
            <%= link_to "Mes soignants et RDV", root_path, class: 'link_color-sidebar' %>
          </div>
        </div>
        <div class="nav-link">
          <div class="media align-items-center">
            <%= link_to ('<i class="fas fa-user fa-2x icon-perso"></i>'.html_safe), root_path, class: "link_color-icon" %>
            <%= link_to "Mon profil", patients_path, class: 'link_color-sidebar' %>
          </div>
        </div>
      </div>
    </li>
  </ul>
</nav>

    
<!-- Sidebar Toggle JS script-->
<script>
    $(document).ready(function () {

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

        });
</script>

app/views/layouts/_top-navbar-doctor.html.erb
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
  <div class="container-fluid">
    <!-- Brand -->
    <a class="mb-0 text-black d-none d-lg-inline-block">Bonjour Docteur <%= current_practionner.last_name %> !</a>
    <!-- User -->
    <div class="dropdown">
      <img src="https://bit.ly/352vL1I" class="float-left rounded-circle avatar-sm">
      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Mon compte
      </button>
      <div class="dropdown-menu">
         <%= link_to "Mon profil", practionners_path, class:"button_color-bipolink" %><br>
         <%= link_to "Paramètres", edit_practionner_path(current_practionner.id), class:"button_color-bipolink" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Se déconnecter", destroy_patient_session_path, class:"button_color-bipolink", method: :delete %>
      </div>
    </div>
  </div>
</nav>

<!-- Dropdown Toggle -->
<script>
  $('.dropdown-toggle').dropdown()
</script>

app/views/layouts/_top-navbar-patient.html.erb
<nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
  <div class="container-fluid">
    <!-- Brand -->
    <a class="mb-0 text-black d-none d-lg-inline-block">Bonjour <%= current_patient.first_name %> !</a>
    <!-- User -->
    <div class="dropdown">
      <img src="https://i.redd.it/6onq25y0sh311.jpg" class="float-left rounded-circle avatar-sm">
      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Mon compte
      </button>
      <div class="dropdown-menu">
         <%= link_to "Mon profil", patients_path, class:"button_color-bipolink" %><br>
         <%= link_to "Paramètres", edit_patient_path(current_patient.id), class:"button_color-bipolink" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Se déconnecter", destroy_patient_session_path, class:"button_color-bipolink", method: :delete %>
      </div>
    </div>
  </div>
</nav>

<!-- Dropdown Toggle -->
<script>
  $('.dropdown-toggle').dropdown()
</script>
<script>
  $(document).ready(function(){
  	$('#nav-icon3').click(function(){
  		$(this).toggleClass('open');
  		});
  	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- FORM DEVICE -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <!-- Bootstrap CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <!-- Our CSS CDN -->
    <link href="side-navbar.css" rel="stylesheet">
    
    <!-- FA kits -->
    <script src="https://kit.fontawesome.com/732403f21f.js" crossorigin="anonymous"></script>
    
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    
    <!-- Bootstrap core JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
  </body>
</html>